### ISSUE TITLE
question: other people can change my armor stands

### ISSUE THREAD

**Issue by MajdT51** [Falyrion/AdvancedArmorStands#9]
Hi again, we are using this plugin [grief-prevention](https://dev.bukkit.org/projects/grief-prevention) for claiming so other players cannot access or change our building and stuff. However, using the command /aa... people can still change the armor stands of others which is not very welcome.

My question is:
1. which plugin should make changes to prevent that, the grief-prevention plugin or the armor stands plugin?
2. Incase those changes are **not** possible, could we add a property "OwnerOf" to the armorstand and then only the owner can change the Poses (I can try to implement that if you are okay with that, but it could add some dependencies on other plugins like this [plugin](https://www.spigotmc.org/resources/nbt-api.7939/) that is used by [AntiMapCopy](https://www.spigotmc.org/resources/antimapcopy-sch%C3%BCtze-deine-maps-und-banner-protect-your-maps-and-banners.94107/) plugin)

**Comment by Falyrion** [comment]
I try to keep the plugin separated from grief-protection functionalities since the plugin is only meant for modifying armor stand. Protection of entities should happen in the grief protection plugin.

However since like every second request i receive is about this topic, it might be useful to implement it. So you can try to add such a feature. Preferably without a small API that gets no further development support in a year.
